---
- name: Install Node.js on remote machines
  hosts:  54.211.238.152 
  become: yes
  tasks:
    - name: Update apt-get
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - software-properties-common

    - name: Add NodeSource repository for Node.js
      shell: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Verify Node.js installation
      command: node -v
      register: node_version

    - name: Display Node.js version
      debug:
        msg: "Node.js version is {{ node_version.stdout }}"

